source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails',        '5.0.0.1'
gem 'puma',         '3.4.0'     # Use Puma as the app server
gem 'sass-rails',   '5.0.6'     # Use SCSS for stylesheets
gem 'uglifier',     '3.0.0'     # Use Uglifier as compressor for JavaScript assets
gem 'coffee-rails', '4.2.1'     # Use CoffeeScript for .coffee assets and views
gem 'jquery-rails', '4.1.1'     # Use jquery as the JavaScript library
gem 'turbolinks',   '5.0.0'
gem 'jbuilder',     '2.4.1'     # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder

group :development, :test do
  gem 'sqlite3',  '1.3.11'    # Use sqlite3 as the database for Active Record
  gem 'byebug',   '9.0.0',    platform: :mri
end

group :development do
  gem 'web-console',    '3.1.1'
  gem 'listen',         '3.0.8'
  gem 'spring',         '1.7.2'
  gem 'spring-watcher-listen', '2.0.0'
end

group :production do
  gem 'pg',   '0.18.4'
end


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]